import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { compile, elaborate, simulate } from '../core/compile.js';
import * as V from '../core/values.js';
import {
  newDoc, normalizeDoc, netlist, generateHdl, schematicFromHdl, symbolPins, symbolDef, modulesFromLibrary,
  mergeNetWires, constBits, SYMBOLS,
} from '../core/schdoc.js';

// ------------------------------------------------------------------ helpers
const FIX = new URL('./fixtures/', import.meta.url);
const read = p => fs.readFileSync(new URL(p, FIX), 'utf8');
const VHDL_FIX = Object.fromEntries(fs.readdirSync(new URL('vhdl/', FIX)).map(f => [`vhdl/${f}`, read(`vhdl/${f}`)]));

// place a symbol and return helpers to get its (sheet) pin positions
function sym(doc, type, x, y, params = {}, name, extra = {}) {
  const s = { id: `S${doc.symbols.length + 1}`, type, x, y, rot: 0, mirror: false, name: name || `U${doc.symbols.length + 1}`, params: { ...params }, ...extra };
  doc.symbols.push(s);
  return s;
}
const pinAt = (doc, s, pin, modules) => { const p = symbolPins(normalizeDoc({ ...doc, symbols: [s] }).symbols[0], modules).find(q => q.name === pin); assert.ok(p, `pin ${pin} of ${s.type}`); return { x: p.x, y: p.y }; };
let wid = 0;
const wire = (doc, ...pts) => doc.wires.push({ id: `W${++wid}`, points: pts.map(p => ({ ...p })) });
const port = (doc, name, dir, x, y, width = 1, type) => { const p = { id: `P${doc.ports.length + 1}`, name, dir, width, x, y }; if (type) p.type = type; doc.ports.push(p); return p; };
// orthogonal wire between two points (horizontal first)
const conn = (doc, a, b, mx = Math.round((a.x + b.x) / 20) * 10) => { if (a.y === b.y || a.x === b.x) wire(doc, a, b); else wire(doc, a, { x: mx, y: a.y }, { x: mx, y: b.y }, b); };

function runSim(files, top, until = 5e6) {
  const srcs = Object.entries(files).map(([path, text]) => ({ path, text }));
  const r = simulate(srcs, top, { until });
  assert.deepEqual(r.errors.map(e => `${e.file}:${e.line} ${e.message}`), [], 'compile/elaboration errors');
  return r;
}
// waveform of each signal of the testbench instance, deltas collapsed
function waves(r) {
  const out = {};
  const inst = r.design.top;
  for (const s of [...inst.signals, ...inst.ports.map(p => p.sig)]) {
    if (!s.wave) continue;
    const pts = [];
    for (let i = 0; i < s.wave.t.length; i++) {
      const t = s.wave.t[i], v = V.toBin(s.wave.v[i]);
      if (pts.length && pts[pts.length - 1][0] === t) pts[pts.length - 1][1] = v;
      else pts.push([t, v]);
    }
    const dedup = pts.filter((p, i) => i === 0 || p[1] !== pts[i - 1][1]);
    out[s.name] = dedup.map(([t, v]) => `${t}:${v}`).join(' ');
  }
  return out;
}
const logOf = r => r.sim.log.map(l => `${l.kind}:${l.text}`);

// HDL -> schematic -> HDL, then simulate both designs with the same testbench
async function roundTrip({ files, module, file, tb, until = 5e6, lang, cutModule, minSymbols = 1, expect }) {
  const srcs = Object.entries(files).map(([path, text]) => ({ path, text }));
  const lib = compile(srcs);
  const d = elaborate(lib, module);
  assert.deepEqual(d.diags.filter(x => x.severity === 'error'), []);
  const modules = modulesFromLibrary(lib, { sources: files });
  const doc = await schematicFromHdl(d.top, { sources: files, modules });
  assert.ok(doc.symbols.length >= minSymbols);
  // the imported schematic is self-consistent
  const nl = netlist(doc, { modules });
  assert.deepEqual(nl.diagnostics.filter(x => x.severity === 'error').map(x => x.message), []);
  if (expect) expect(doc, nl);
  // JSON round trip of the document itself
  const doc2 = normalizeDoc(JSON.parse(JSON.stringify(doc)));
  const gen = generateHdl(doc2, { lang, modules });
  assert.deepEqual(gen.diagnostics.filter(x => x.severity === 'error').map(x => x.message), []);
  assert.match(gen.code, /Generated by XAIlinx from .*\.sch\.json — kept in sync with the schematic/);
  // regenerated sources: replace the module
  const regen = { ...files };
  if (cutModule) regen[file] = files[file].replace(new RegExp(`module\\s+${module}\\b[\\s\\S]*?endmodule`), '');
  else delete regen[file];
  regen[`gen/${gen.filename}`] = gen.code;
  // the generated design parses and elaborates cleanly
  const lib2 = compile(Object.entries(regen).map(([path, text]) => ({ path, text })));
  assert.deepEqual(lib2.errors.filter(e => e.severity === 'error').map(e => `${e.file}:${e.line} ${e.message}`), [], gen.code);
  const d2 = elaborate(lib2, module);
  assert.deepEqual(d2.diags.filter(e => e.severity === 'error').map(e => e.message), [], gen.code);
  // simulate both
  const a = runSim(files, tb, until), b = runSim(regen, tb, until);
  const wa = waves(a), wb = waves(b);
  assert.ok(Object.keys(wa).length > 0);
  assert.ok(Object.values(wa).some(w => w.split(' ').length > 4), 'testbench produces activity');
  assert.deepEqual(wb, wa, `waveforms differ for ${module}\n${gen.code}`);
  assert.deepEqual(logOf(b), logOf(a));
  return { doc, gen, a, b };
}

// ------------------------------------------------------------------ netlist
test('netlist: pins, T-junctions, labels and I/O markers', () => {
  const doc = newDoc('nl', 'vhdl');
  const g = sym(doc, 'and2', 200, 100);
  const n = sym(doc, 'inv', 400, 110);
  port(doc, 'a', 'in', 100, 110);
  port(doc, 'b', 'in', 100, 300);
  port(doc, 'y', 'out', 600, 120);
  const I0 = pinAt(doc, g, 'I0'), I1 = pinAt(doc, g, 'I1'), O = pinAt(doc, g, 'O');
  conn(doc, { x: 100, y: 110 }, I0);
  // b goes to I1 through a T-junction on a vertical wire
  wire(doc, { x: 100, y: 300 }, { x: 150, y: 300 }, { x: 150, y: 200 });
  wire(doc, { x: 150, y: 200 }, { x: 150, y: 130 }, I1);
  conn(doc, O, pinAt(doc, n, 'I'));
  // inverter output: wire with a label "nx", the output marker is connected through another label "nx"
  const nO = pinAt(doc, n, 'O');
  wire(doc, nO, { x: nO.x + 40, y: nO.y });
  doc.labels.push({ id: 'L1', x: nO.x + 20, y: nO.y, net: 'nx' });
  wire(doc, { x: 560, y: 120 }, { x: 600, y: 120 });
  doc.labels.push({ id: 'L2', x: 570, y: 120, net: 'nx' });
  // dangling wire + an unconnected label
  wire(doc, { x: 800, y: 800 }, { x: 900, y: 800 });
  const nl = netlist(doc);
  const pn = (s, p) => nl.pinNet.get(`${s.id}/${p}`);
  assert.equal(pn(g, 'I0').name, 'a');
  assert.equal(pn(g, 'I1').name, 'b');
  assert.equal(pn(n, 'I'), pn(g, 'O'));
  assert.ok(pn(n, 'I').auto);
  assert.equal(pn(n, 'O').name, 'y', 'label joins the output marker net (marker name wins)');
  assert.ok(nl.diagnostics.some(d => /dangling/.test(d.message)));
  assert.ok(nl.diagnostics.some(d => /also named 'nx'/.test(d.message)));
  // T junction: one dot where three branches meet? (b wire corner is a 2-way corner, not a junction)
  assert.equal(nl.junctions.length, 0);
});

test('netlist: multiple drivers, width mismatch, unconnected input, junction dots', () => {
  const doc = newDoc('nl2', 'verilog');
  const a = sym(doc, 'inv', 100, 100);
  const b = sym(doc, 'inv', 100, 200);
  const c = sym(doc, 'buf', 300, 300, { width: 4 });
  const oa = pinAt(doc, a, 'O'), ob = pinAt(doc, b, 'O');
  wire(doc, oa, { x: 200, y: oa.y }, { x: 200, y: ob.y }, ob);
  wire(doc, { x: 200, y: 150 }, { x: 250, y: 150 });   // T on the vertical part
  const ci = pinAt(doc, c, 'I');
  wire(doc, { x: 250, y: 150 }, { x: 250, y: ci.y }, ci);
  const nl = netlist(doc);
  const msgs = nl.diagnostics.map(d => d.message).join('\n');
  assert.match(msgs, /has 2 drivers/);
  assert.match(msgs, /width mismatch/);
  assert.match(msgs, /input pin I of U1 .* not connected/);
  assert.equal(nl.pinNet.get(`${a.id}/O`), nl.pinNet.get(`${c.id}/I`));
  assert.deepEqual(nl.junctions, [{ x: 200, y: 150 }]);
});

test('netlist: rotation and mirroring move the pins', () => {
  const s = normalizeDoc({ symbols: [{ id: 'S1', type: 'and2', x: 100, y: 100, rot: 90 }] }).symbols[0];
  const pins = symbolPins(s);
  const def = symbolDef(s);
  // rotated 90° clockwise: inputs on top, output at the bottom
  assert.ok(pins.filter(p => p.dir === 'in').every(p => p.y === 100 && p.side === 'N'));
  assert.equal(pins.find(p => p.name === 'O').y, 100 + def.w);
  const m = normalizeDoc({ symbols: [{ id: 'S1', type: 'and2', x: 0, y: 0, mirror: true }] }).symbols[0];
  assert.equal(symbolPins(m).find(p => p.name === 'O').x, 0);
  assert.equal(symbolPins(m).find(p => p.name === 'O').side, 'W');
});

test('mergeNetWires splits overlapping routes at junctions', () => {
  const lines = mergeNetWires([
    [{ x: 0, y: 0 }, { x: 100, y: 0 }, { x: 100, y: 100 }],
    [{ x: 0, y: 0 }, { x: 100, y: 0 }, { x: 100, y: 50 }, { x: 200, y: 50 }],
  ]);
  const doc = normalizeDoc({ wires: lines.map((points, i) => ({ id: `W${i}`, points })) });
  const nl = netlist(doc);
  assert.equal(nl.nets.length, 1);
  assert.deepEqual(nl.junctions, [{ x: 100, y: 50 }]);
});

test('constBits parses HDL-neutral constants', () => {
  assert.equal(constBits('5', 4), '0101');
  assert.equal(constBits('0xA', 8), '00001010');
  assert.equal(constBits('0b1x', 2), '1x');
  assert.equal(constBits("'1'", 1), '1');
  assert.equal(constBits("8'hFF", 8), '11111111');
  assert.equal(constBits('-1', 4), '1111');
});

// ------------------------------------------------------------------ generateHdl from drawn schematics
function gateDoc(lang) {
  // y = (a and b) or not c ; z = a xor b (4-bit buses through a mux)
  const doc = newDoc('gates', lang);
  const and = sym(doc, 'and2', 200, 100);
  const inv = sym(doc, 'inv', 200, 200);
  const or = sym(doc, 'or2', 400, 120);
  const mx = sym(doc, 'mux2', 400, 300, { width: 4 });
  port(doc, 'a', 'in', 100, 110); port(doc, 'b', 'in', 100, 130); port(doc, 'c', 'in', 100, 210);
  port(doc, 'd0', 'in', 100, 320, 4); port(doc, 'd1', 'in', 100, 340, 4);
  port(doc, 'y', 'out', 600, 140); port(doc, 'q', 'out', 600, 330, 4);
  conn(doc, { x: 100, y: 110 }, pinAt(doc, and, 'I0'));
  conn(doc, { x: 100, y: 130 }, pinAt(doc, and, 'I1'));
  conn(doc, { x: 100, y: 210 }, pinAt(doc, inv, 'I'));
  conn(doc, pinAt(doc, and, 'O'), pinAt(doc, or, 'I0'));
  conn(doc, pinAt(doc, inv, 'O'), pinAt(doc, or, 'I1'));
  conn(doc, pinAt(doc, or, 'O'), { x: 600, y: 140 });
  conn(doc, { x: 100, y: 320 }, pinAt(doc, mx, 'D0'));
  conn(doc, { x: 100, y: 340 }, pinAt(doc, mx, 'D1'));
  conn(doc, pinAt(doc, mx, 'O'), { x: 600, y: 330 });
  // select = the 'or' output via a label
  const s = pinAt(doc, mx, 'S0');
  wire(doc, s, { x: s.x, y: s.y + 30 });
  doc.labels.push({ id: 'L1', x: s.x, y: s.y + 30, net: 'y' });
  return doc;
}

for (const lang of ['vhdl', 'verilog']) {
  test(`generateHdl ${lang}: gate circuit simulates correctly`, () => {
    const doc = gateDoc(lang);
    const g = generateHdl(doc, { lang });
    assert.deepEqual(g.diagnostics.filter(d => d.severity === 'error'), [], g.code);
    assert.equal(g.filename, lang === 'vhdl' ? 'gates.vhd' : 'gates.v');
    assert.match(g.code, /Generated by XAIlinx from gates\.sch\.json/);
    const tb = lang === 'vhdl' ? `
library ieee; use ieee.std_logic_1164.all;
entity tb is end;
architecture s of tb is
  signal a, b, c, y : std_logic; signal d0, d1, q : std_logic_vector(3 downto 0);
begin
  u : entity work.gates port map (a => a, b => b, c => c, d0 => d0, d1 => d1, y => y, q => q);
  process
    type v is array (0 to 7) of std_logic_vector(2 downto 0);
    constant cases : v := ("000", "001", "010", "011", "100", "101", "110", "111");
  begin
    d0 <= "0101"; d1 <= "1010";
    for i in 0 to 7 loop
      a <= cases(i)(2); b <= cases(i)(1); c <= cases(i)(0);
      wait for 10 ns;
      assert y = ((cases(i)(2) and cases(i)(1)) or not cases(i)(0)) report "bad y" severity error;
      if y = '1' then assert q = "1010" report "bad q" severity error; else assert q = "0101" report "bad q0" severity error; end if;
    end loop;
    report "done";
    wait;
  end process;
end;` : `
module tb;
  reg a, b, c; reg [3:0] d0 = 4'b0101, d1 = 4'b1010; wire y; wire [3:0] q; integer i, errs = 0;
  gates u (.a(a), .b(b), .c(c), .d0(d0), .d1(d1), .y(y), .q(q));
  initial begin
    for (i = 0; i < 8; i = i + 1) begin
      {a, b, c} = i; #10;
      if (y !== ((a & b) | ~c)) errs = errs + 1;
      if (q !== (y ? d1 : d0)) errs = errs + 1;
    end
    $display("errs=%0d", errs);
  end
endmodule`;
    const r = runSim({ [g.filename]: g.code, [lang === 'vhdl' ? 'tb.vhd' : 'tb.v']: tb }, 'tb');
    const log = logOf(r);
    assert.deepEqual(r.sim.log.filter(l => l.kind === 'error' || l.kind === 'failure'), [], g.code);
    if (lang === 'verilog') assert.ok(log.includes('print:errs=0'), log.join('\n'));
    else assert.ok(log.includes('note:done'), log.join('\n'));
  });

  test(`generateHdl ${lang}: register + adder counter with clock and reset`, () => {
    // q <= q + 1 every clock when en, async reset
    const doc = newDoc('cnt8', lang);
    const reg = sym(doc, 'register', 400, 300, { width: 8, en: true, reset: 'async', init: '0' });   // D 310, CE 330, C 350, CLR 370, Q (490,310)
    const add = sym(doc, 'add', 200, 100, { width: 8 });                                            // A (200,110) B (200,130) S (280,130)
    const one = sym(doc, 'constant', 60, 200, { value: '1', width: 8 });                              // O (100,210)
    port(doc, 'clk', 'in', 100, 400); port(doc, 'rst', 'in', 100, 440); port(doc, 'en', 'in', 100, 480);
    port(doc, 'q', 'out', 700, 310, 8);
    conn(doc, pinAt(doc, add, 'S'), pinAt(doc, reg, 'D'), 340);
    conn(doc, pinAt(doc, one, 'O'), pinAt(doc, add, 'B'), 150);
    conn(doc, { x: 100, y: 480 }, pinAt(doc, reg, 'CE'), 370);
    conn(doc, { x: 100, y: 400 }, pinAt(doc, reg, 'C'), 360);
    conn(doc, { x: 100, y: 440 }, pinAt(doc, reg, 'CLR'), 380);
    const Q = pinAt(doc, reg, 'Q');
    wire(doc, Q, { x: 700, y: 310 });
    // feedback q -> add.A via a net label 'q'
    const A = pinAt(doc, add, 'A');
    wire(doc, { x: A.x - 30, y: A.y }, A);
    doc.labels.push({ id: 'L1', x: A.x - 30, y: A.y, net: 'q' });
    const g = generateHdl(doc, { lang });
    assert.deepEqual(g.diagnostics.filter(d => d.severity !== 'info').map(d => d.message), [], g.code);
    const tb = lang === 'vhdl' ? `
library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all;
entity tb is end;
architecture s of tb is
  signal clk : std_logic := '0'; signal rst : std_logic := '1'; signal en : std_logic := '0'; signal q : std_logic_vector(7 downto 0);
begin
  clk <= not clk after 5 ns;
  u : entity work.cnt8 port map (clk => clk, rst => rst, en => en, q => q);
  process begin
    wait for 12 ns; rst <= '0'; en <= '1';
    for i in 1 to 20 loop wait until rising_edge(clk); end loop;
    wait for 1 ns;
    report "q=" & integer'image(to_integer(unsigned(q)));
    en <= '0'; wait for 50 ns;
    report "q=" & integer'image(to_integer(unsigned(q)));
    rst <= '1'; wait for 1 ns;
    report "q=" & integer'image(to_integer(unsigned(q)));
    wait;
  end process;
end;` : `
\`timescale 1ns/1ps
module tb;
  reg clk = 0, rst = 1, en = 0; wire [7:0] q;
  cnt8 u (.clk(clk), .rst(rst), .en(en), .q(q));
  always #5 clk = ~clk;
  initial begin
    #12 rst = 0; en = 1;
    repeat (20) @(posedge clk);
    #1 $display("q=%0d", q);
    en = 0; #50 $display("q=%0d", q);
    rst = 1; #1 $display("q=%0d", q);
    $finish;
  end
endmodule`;
    const r = runSim({ [g.filename]: g.code, [lang === 'vhdl' ? 'tb.vhd' : 'tb.v']: tb }, 'tb', 1e6);
    const log = logOf(r).map(l => l.replace(/^(note|print):/, ''));
    assert.deepEqual(log.filter(l => l.startsWith('q=')), ['q=20', 'q=20', 'q=0'], g.code);
  });

  test(`generateHdl ${lang}: module instance with named association`, () => {
    const sub = lang === 'vhdl'
      ? { 'half.vhd': 'library ieee; use ieee.std_logic_1164.all;\nentity half is port (x, y : in std_logic; s, c : out std_logic); end;\narchitecture a of half is begin s <= x xor y; c <= x and y; end;' }
      : { 'half.v': 'module half(input x, input y, output s, output c); assign s = x ^ y; assign c = x & y; endmodule' };
    const lib = compile(Object.entries(sub).map(([path, text]) => ({ path, text })));
    const modules = modulesFromLibrary(lib, { sources: sub });
    assert.deepEqual(modules.half.ports.map(p => [p.name, p.dir, p.width]), [['x', 'in', 1], ['y', 'in', 1], ['s', 'out', 1], ['c', 'out', 1]]);
    const doc = newDoc('wrap', lang);
    const h = sym(doc, 'module', 300, 100, { module: 'half', generics: {} }, 'u_half');
    const g2 = sym(doc, 'gnd', 200, 250);
    port(doc, 'a', 'in', 100, 120); port(doc, 'sum', 'out', 600, 120); port(doc, 'carry', 'out', 600, 140);
    conn(doc, { x: 100, y: 120 }, pinAt(doc, h, 'x', modules));
    conn(doc, pinAt(doc, g2, 'G'), pinAt(doc, h, 'y', modules));
    conn(doc, pinAt(doc, h, 's', modules), { x: 600, y: 120 });
    conn(doc, pinAt(doc, h, 'c', modules), { x: 600, y: 140 });
    const g = generateHdl(doc, { lang, modules });
    assert.deepEqual(g.diagnostics.filter(d => d.severity === 'error'), [], g.code);
    if (lang === 'vhdl') assert.match(g.code, /u_half : entity work\.half\s+port map \(\s+x => a,\s+y => net_\d+,\s+s => sum,\s+c => carry/);
    else assert.match(g.code, /half u_half \(\s+\.x\(a\),\s+\.y\(net_\d+\),\s+\.s\(sum\),\s+\.c\(carry\)/);
    const tb = lang === 'vhdl'
      ? 'library ieee; use ieee.std_logic_1164.all;\nentity tb is end;\narchitecture s of tb is signal a, s, c : std_logic; begin\n u : entity work.wrap port map (a => a, sum => s, carry => c);\n process begin a <= \'0\'; wait for 1 ns; report std_logic\'image(s) & std_logic\'image(c); a <= \'1\'; wait for 1 ns; report std_logic\'image(s) & std_logic\'image(c); wait; end process;\nend;'
      : 'module tb; reg a; wire s, c; wrap u(.a(a), .sum(s), .carry(c)); initial begin a = 0; #1 $display("%b%b", s, c); a = 1; #1 $display("%b%b", s, c); end endmodule';
    const r = runSim({ ...sub, [g.filename]: g.code, [lang === 'vhdl' ? 'tb.vhd' : 'tb.v']: tb }, 'tb');
    const out = logOf(r).map(l => l.replace(/^(note|print):/, '').replace(/'/g, ''));
    assert.deepEqual(out.slice(0, 2), ['00', '10']);
  });
}

test('generateHdl: hdlblock pins aliased to differently named nets, wrong-language block is an error', () => {
  const doc = newDoc('blk', 'vhdl');
  const b = sym(doc, 'hdlblock', 300, 100, { title: 'inv', inputs: [{ name: 'x', width: 1 }], outputs: [{ name: 'y', width: 1 }] }, 'B1', { hdl: 'y <= not x;' });
  port(doc, 'a', 'in', 100, 120); port(doc, 'z', 'out', 600, 120);
  conn(doc, { x: 100, y: 120 }, pinAt(doc, b, 'x'));
  conn(doc, pinAt(doc, b, 'y'), { x: 600, y: 120 });
  const g = generateHdl(doc);
  assert.match(g.code, /x <= a;/);
  assert.match(g.code, /z <= y;/);
  assert.match(g.code, /y <= not x;/);
  const r = runSim({ 'blk.vhd': g.code, 'tb.vhd': 'library ieee; use ieee.std_logic_1164.all; entity tb is end; architecture s of tb is signal a, z : std_logic; begin u : entity work.blk port map (a, z); process begin a <= \'0\'; wait for 1 ns; assert z = \'1\' severity failure; report "ok"; wait; end process; end;' }, 'tb');
  assert.ok(logOf(r).includes('note:ok'));
  const v = generateHdl(doc, { lang: 'verilog' });
  assert.ok(v.diagnostics.some(d => d.severity === 'error' && /HDL blocks contain VHDL/.test(d.message)));
});

// ------------------------------------------------------------------ round trips HDL -> schematic -> HDL
const TB_FSM = `
library ieee; use ieee.std_logic_1164.all;
entity tb_fsm is end;
architecture s of tb_fsm is
  signal clk : std_logic := '0'; signal reset : std_logic := '1'; signal x, found : std_logic := '0';
  constant pat : std_logic_vector(0 to 15) := "1011010110011010";
begin
  clk <= not clk after 5 ns;
  dut : entity work.seq_detect port map (clk => clk, reset => reset, x => x, found => found);
  process begin
    wait for 12 ns; reset <= '0';
    for i in pat'range loop x <= pat(i); wait until falling_edge(clk); end loop;
    std.env.finish;
  end process;
end;`;
const TB_REG = `
library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all;
entity tb_reg is end;
architecture s of tb_reg is
  signal clk : std_logic := '0'; signal clr : std_logic := '1'; signal load : std_logic := '0';
  signal d, q : std_logic_vector(7 downto 0) := (others => '0');
begin
  clk <= not clk after 5 ns;
  dut : entity work.reg_n generic map (N => 8) port map (clk => clk, clr => clr, load => load, d => d, q => q);
  process begin
    wait for 7 ns; clr <= '0';
    for i in 0 to 9 loop d <= std_logic_vector(to_unsigned(i * 37 mod 256, 8)); load <= '1' when i mod 3 /= 0 else '0'; wait for 10 ns; end loop;
    clr <= '1'; wait for 3 ns; clr <= '0'; wait for 20 ns;
    std.env.finish;
  end process;
end;`;
const TB_SEG = `
library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all;
entity tb_seg is end;
architecture s of tb_seg is signal hex : std_logic_vector(3 downto 0); signal seg : std_logic_vector(6 downto 0);
begin
  dut : entity work.seg7 port map (hex => hex, seg => seg);
  process begin
    for i in 0 to 15 loop hex <= std_logic_vector(to_unsigned(i, 4)); wait for 10 ns; end loop;
    wait;
  end process;
end;`;
const TB_TOP = `
library ieee; use ieee.std_logic_1164.all;
entity tb_top is end;
architecture s of tb_top is
  signal clk : std_logic := '0'; signal btn, sw : std_logic_vector(3 downto 0) := "0001"; signal led : std_logic_vector(7 downto 0);
begin
  clk <= not clk after 5 ns;
  dut : entity work.top port map (clk => clk, btn => btn, sw => sw, led => led);
  process begin
    wait for 22 ns; btn <= "0000"; sw <= "0101";
    wait for 100 ns; sw <= "1010"; btn <= "0010";
    wait for 60 ns; btn <= "0110";
    wait for 60 ns; btn <= "1110"; sw <= "1111";
    wait for 80 ns; btn <= "1100";
    wait for 40 ns;
    std.env.finish;
  end process;
end;`;

test('round trip VHDL counter (fixture testbench)', async () => {
  const { doc, gen } = await roundTrip({ files: VHDL_FIX, module: 'counter', file: 'vhdl/counter.vhd', tb: 'tb_counter', until: 2e6 });
  assert.ok(doc.symbols.every(s => s.type === 'hdlblock'));
  assert.match(gen.code, /architecture Behavioral of counter/);
  assert.match(gen.code, /generic \(\s+WIDTH : integer := 8/);
});

test('round trip VHDL two-process FSM', async () => {
  const files = { ...VHDL_FIX, 'tb_fsm.vhd': TB_FSM };
  await roundTrip({ files, module: 'seq_detect', file: 'vhdl/fsm.vhd', tb: 'tb_fsm', until: 1e6 });
});

test('round trip VHDL generic register', async () => {
  const files = { ...VHDL_FIX, 'tb_reg.vhd': TB_REG };
  await roundTrip({ files, module: 'reg_n', file: 'vhdl/reg_n.vhd', tb: 'tb_reg', until: 1e6 });
});

test('round trip VHDL 7-segment decoder (with-select)', async () => {
  const files = { ...VHDL_FIX, 'tb_seg.vhd': TB_SEG };
  await roundTrip({ files, module: 'seg7', file: 'vhdl/seg7.vhd', tb: 'tb_seg', until: 1e6 });
});

test('round trip VHDL structural top (instance, constant, bus tap, generate)', async () => {
  const files = { ...VHDL_FIX, 'tb_top.vhd': TB_TOP };
  await roundTrip({
    files, module: 'top', file: 'vhdl/top.vhd', tb: 'tb_top', until: 1e6,
    expect: doc => {
      const types = doc.symbols.map(s => s.type);
      assert.ok(types.includes('module'));
      assert.ok(types.includes('slice'));
      assert.ok(types.includes('constant'));
      assert.ok(types.includes('hdlblock'));
      const u = doc.symbols.find(s => s.type === 'module');
      assert.equal(u.name, 'u_cnt');
      assert.equal(u.params.module, 'counter');
    },
  });
});

const VLOG_FILES = { 'verilog/counter_top.v': read('verilog/counter_top.v'), 'verilog/tb_counter.v': read('verilog/tb_counter.v') };
const TB_VTOP = '`timescale 1ns/1ps\nmodule tb_vtop; reg clk = 0; wire [7:0] led; wire [3:0] x; top dut(.clk(clk), .led(led), .x(x)); always #5 clk = ~clk; initial #3000 $finish; endmodule';

test('round trip Verilog counter (fixture testbench)', async () => {
  await roundTrip({ files: VLOG_FILES, module: 'counter', file: 'verilog/counter_top.v', tb: 'tb', cutModule: true, until: 1e6 });
});

test('round trip Verilog top (instance with constant ports, generate of gate primitives)', async () => {
  const files = { ...VLOG_FILES, 'tb_vtop.v': TB_VTOP };
  await roundTrip({
    files, module: 'top', file: 'verilog/counter_top.v', tb: 'tb_vtop', cutModule: true, until: 1e7,
    expect: doc => {
      assert.ok(doc.symbols.some(s => s.type === 'module' && s.params.module === 'counter' && s.params.generics.N === '8'));
      assert.equal(doc.symbols.filter(s => s.type === 'constant').length, 2);
    },
  });
});

const GATES_V = `
module fa(input a, input b, input ci, output s, output co);
  assign s = a ^ b ^ ci;
  assign co = (a & b) | (ci & (a ^ b));
endmodule
module gl(input [3:0] x, input [3:0] y, input sel, input c0, output [3:0] z, output [3:0] m, output n, output [7:0] w, output c4);
  wire [3:0] c;
  wire t = x[0] & ~y[0];
  assign z = ~(x | y);
  assign m = sel ? x : y;
  assign n = t ^ x[3];
  assign w = {x, y[3:2], 2'b10};
  fa f0 (.a(x[0]), .b(y[0]), .ci(c0), .s(c[0]), .co(c[1]));
  fa f1 (.a(x[1]), .b(y[1]), .ci(c[1]), .s(), .co(c4));
endmodule
module tb_gl;
  reg [3:0] x, y; reg sel, c0; wire [3:0] z, m; wire n, c4; wire [7:0] w; integer i;
  gl dut(.x(x), .y(y), .sel(sel), .c0(c0), .z(z), .m(m), .n(n), .w(w), .c4(c4));
  initial begin
    for (i = 0; i < 300; i = i + 1) begin {sel, c0, x, y} = i * 7; #5; end
    $finish;
  end
endmodule`;

test('round trip inline Verilog gate-level design (gates, mux, slices, concat, instances)', async () => {
  const files = { 'gl.v': GATES_V };
  const { doc } = await roundTrip({
    files, module: 'gl', file: 'gl.v', tb: 'tb_gl', cutModule: true, until: 1e7,
    expect: d => {
      const t = d.symbols.map(s => s.type);
      // x[0] & ~y[0] -> AND2B1
      for (const k of ['nor2', 'mux2', 'and2b1', 'xor2', 'busjoin', 'slice', 'module', 'constant']) assert.ok(t.includes(k), `has ${k}: ${t.join(',')}`);
    },
  });
  assert.ok(doc.symbols.filter(s => s.type === 'hdlblock').length <= 1);
});

const GATES_VHD = `
library ieee; use ieee.std_logic_1164.all;
entity glv is
  port (a, b, c : in std_logic; v : in std_logic_vector(3 downto 0); s : in std_logic;
        y : out std_logic; z : out std_logic_vector(3 downto 0); p : out std_logic_vector(1 downto 0); k : out std_logic);
end;
architecture rtl of glv is
  signal t : std_logic;
begin
  t <= (a and b) or (not c);
  y <= t xor a;
  z <= v when s = '1' else not v;
  p <= v(3 downto 2) and v(1 downto 0);
  k <= a nand c;
end;
library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all;
entity tb_glv is end;
architecture s of tb_glv is
  signal a, b, c, s, y, k : std_logic; signal v, z : std_logic_vector(3 downto 0); signal p : std_logic_vector(1 downto 0);
  signal cnt : unsigned(7 downto 0) := (others => '0');
begin
  dut : entity work.glv port map (a, b, c, v, s, y, z, p, k);
  a <= cnt(0); b <= cnt(1); c <= cnt(2); s <= cnt(3); v <= std_logic_vector(cnt(7 downto 4));
  process begin
    for i in 0 to 255 loop cnt <= to_unsigned(i, 8); wait for 5 ns; end loop;
    wait;
  end process;
end;`;

test('round trip inline VHDL gate-level design', async () => {
  const files = { 'glv.vhd': GATES_VHD.split('library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all;\nentity tb_glv')[0], 'tb_glv.vhd': 'library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all;\nentity tb_glv' + GATES_VHD.split('entity tb_glv')[1] };
  const { doc } = await roundTrip({
    files, module: 'glv', file: 'glv.vhd', tb: 'tb_glv', until: 1e7,
    expect: d => {
      const t = d.symbols.map(s => s.type);
      // (a and b) or (not c) -> OR2B1
      for (const k of ['and2', 'or2b1', 'inv', 'xor2', 'mux2', 'nand2', 'slice']) assert.ok(t.includes(k), `has ${k}: ${t.join(',')}`);
    },
  });
  assert.equal(doc.symbols.filter(s => s.type === 'hdlblock').length, 0);
});

test('schematicFromHdl uses a supplied ELK-style layout function', async () => {
  const files = { 'glv.vhd': GATES_VHD.split('library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all;\nentity tb_glv')[0] };
  const lib = compile([{ path: 'glv.vhd', text: files['glv.vhd'] }]);
  const d = elaborate(lib, 'glv');
  let called = 0;
  // fake layout: place nodes in a diagonal, no routes (forces the fallback for wires)
  const layout = async g => { called++; return { children: g.children.map((c, i) => ({ id: c.id, x: 100 + i * 150, y: 100 + i * 90 })), edges: [] }; };
  const doc = await schematicFromHdl(d.top, { sources: files, layout });
  assert.equal(called, 1);
  const nl = netlist(doc);
  assert.deepEqual(nl.diagnostics.filter(x => x.severity === 'error').map(x => x.message), []);
  const g = generateHdl(doc);
  assert.deepEqual(g.diagnostics.filter(x => x.severity === 'error'), []);
});

test('symbol library covers the documented set', () => {
  for (const t of ['and2', 'and5', 'or5', 'nand4', 'nor4', 'xor2', 'xnor2', 'inv', 'buf', 'mux2', 'mux4', 'add', 'sub', 'compare', 'constant', 'vcc', 'gnd', 'fd', 'fdc', 'fdce', 'fdre', 'register', 'counter', 'slice', 'busjoin', 'module', 'hdlblock'])
    assert.ok(SYMBOLS[t], t);
  for (const t of Object.keys(SYMBOLS)) {
    const def = symbolDef({ type: t, params: {} });
    for (const p of def.pins) assert.ok(p.x % 10 === 0 && p.y % 10 === 0, `${t}.${p.name} on grid`);
    assert.ok(def.w % 10 === 0 && def.h % 10 === 0, `${t} size on grid`);
  }
});
