// Xilinx UCF (User Constraints File) generation and parsing.
//
// Isomorphic module: no Node APIs, imported both by the server and the browser.
//
// Bus naming convention: HDL port `led[7:0]`, bit 3  ->  UCF net `led<3>`.
//
// Assignment object (per net / per bit):
//   { loc: 'F12', iostandard: 'LVCMOS33', pull: 'up'|'down'|'keeper'|null,
//     drive: 8, slew: 'slow'|'fast'|'quietio', clockDedicatedRoute: false }
// Clock object:
//   { net: 'clk', period: 20 (ns, number or '20 ns'/'50 MHz' string), duty: 50, name: 'TS_clk' }

/** UCF net name for one bit of a port (`bit` undefined/null for scalars). */
export function bitName(port, bit) {
  return bit === undefined || bit === null ? port : `${port}<${bit}>`;
}

/**
 * Normalise a port description to { name, dir, msb, lsb, width, bus }.
 * Accepts a string ('led', 'led[7:0]', 'led<7:0>') or an object
 * ({ name, dir?, width?, msb?, lsb?, range?:[msb,lsb] }).
 */
export function normalizePort(p) {
  if (typeof p === 'string') {
    const m = /^\s*([A-Za-z_][\w$]*)\s*(?:[[<]\s*(-?\d+)\s*:\s*(-?\d+)\s*[\]>])?\s*$/.exec(p);
    if (!m) throw new Error(`bad port spec '${p}'`);
    if (m[2] === undefined) return { name: m[1], msb: null, lsb: null, width: 1, bus: false };
    const msb = +m[2], lsb = +m[3];
    return { name: m[1], msb, lsb, width: Math.abs(msb - lsb) + 1, bus: true };
  }
  const name = p.name;
  let msb = p.msb ?? (Array.isArray(p.range) ? p.range[0] : null);
  let lsb = p.lsb ?? (Array.isArray(p.range) ? p.range[1] : null);
  if (msb === null && p.width > 1) { msb = p.width - 1; lsb = 0; }
  const bus = msb !== null && msb !== undefined && (p.bus !== false);
  if (!bus) return { name, dir: p.dir, msb: null, lsb: null, width: 1, bus: false };
  lsb ??= 0;
  return { name, dir: p.dir, msb, lsb, width: Math.abs(msb - lsb) + 1, bus: true };
}

/** All UCF net names of a port, LSB first. */
export function expandPort(p) {
  const n = normalizePort(p);
  if (!n.bus) return [n.name];
  const out = [];
  const step = n.msb >= n.lsb ? 1 : -1;
  for (let i = n.lsb; ; i += step) { out.push(bitName(n.name, i)); if (i === n.msb) break; }
  return out;
}

/** Parse '20', '20 ns', '20ns', '50 MHz', '1.5 us' into nanoseconds (number). */
export function periodNs(v) {
  if (typeof v === 'number') return v;
  const m = /^\s*([\d.]+)\s*(ps|ns|us|ms|s|hz|khz|mhz|ghz)?\s*$/i.exec(String(v ?? ''));
  if (!m) throw new Error(`bad clock period '${v}'`);
  const x = parseFloat(m[1]);
  switch ((m[2] || 'ns').toLowerCase()) {
    case 'ps': return x / 1000;
    case 'ns': return x;
    case 'us': return x * 1e3;
    case 'ms': return x * 1e6;
    case 's': return x * 1e9;
    case 'hz': return 1e9 / x;
    case 'khz': return 1e6 / x;
    case 'mhz': return 1e3 / x;
    case 'ghz': return 1 / x;
  }
  return x;
}

const fmtNum = x => String(+x.toFixed(6));

// Net names that need no quoting are still always quoted in our output (ISE accepts both).
const q = s => `"${String(s).replace(/"/g, '')}"`;

function attrList(a) {
  const parts = [];
  if (a.loc) parts.push(`LOC = ${q(String(a.loc).toUpperCase())}`);
  if (a.iostandard) parts.push(`IOSTANDARD = ${String(a.iostandard).toUpperCase()}`);
  const pull = a.pull ? String(a.pull).toLowerCase() : '';
  if (pull === 'up' || pull === 'pullup') parts.push('PULLUP');
  else if (pull === 'down' || pull === 'pulldown') parts.push('PULLDOWN');
  else if (pull === 'keeper') parts.push('KEEPER');
  if (a.drive !== undefined && a.drive !== null && a.drive !== '') parts.push(`DRIVE = ${parseInt(a.drive, 10)}`);
  if (a.slew) parts.push(`SLEW = ${String(a.slew).toUpperCase()}`);
  return parts;
}

/**
 * Generate UCF text.
 * @param {object} o
 * @param {Array}  [o.ports]        ports in HDL order (strings or objects, see normalizePort). When
 *                                  given, nets are emitted in port order and unassigned bits are
 *                                  listed as comments; when omitted every assignment is emitted.
 * @param {object} o.assignments    { netName: assignment }
 * @param {Array}  [o.clocks]       [{ net, period, duty?, name? }]
 * @param {string} [o.header]       comment text placed at the top
 */
export function generateUcf({ ports, assignments = {}, clocks = [], header } = {}) {
  const lines = [];
  for (const h of (header ?? 'Generated by XAIlinx').split('\n')) lines.push(`# ${h}`.trimEnd());
  lines.push('');

  let nets;
  if (ports && ports.length) {
    nets = [];
    for (const p of ports) {
      const n = normalizePort(p);
      const bits = expandPort(n);
      // Allow a scalar assignment for a 1-bit bus declared as `x[0:0]` and vice versa.
      for (const b of bits) nets.push(b);
    }
    // Extra assignments not matching any port are still emitted (kept, but flagged).
    const known = new Set(nets);
    const extra = Object.keys(assignments).filter(k => !known.has(k));
    if (extra.length) nets.push(...extra.map(e => ({ extra: e })));
  } else {
    nets = Object.keys(assignments).sort(netCompare);
  }

  const w = Math.max(8, ...nets.map(n => (typeof n === 'string' ? n : n.extra).length + 2));
  for (const n of nets) {
    const name = typeof n === 'string' ? n : n.extra;
    const a = assignments[name];
    if (!a || !a.loc && !a.iostandard && !a.pull && !a.drive && !a.slew) {
      lines.push(`# NET ${q(name).padEnd(w)} LOC = "" ;  # unassigned`);
      continue;
    }
    const attrs = attrList(a);
    const suffix = typeof n === 'string' ? '' : '  # not a port of the top module';
    lines.push(`NET ${q(name).padEnd(w)} ${attrs.join(' | ')} ;${suffix}`);
    if (a.clockDedicatedRoute === false || a.clockDedicatedRoute === 'FALSE')
      lines.push(`NET ${q(name).padEnd(w)} CLOCK_DEDICATED_ROUTE = FALSE ;`);
  }

  if (clocks.length) {
    lines.push('', '# Timing constraints');
    for (const c of clocks) {
      const ns = periodNs(c.period);
      const duty = c.duty ?? 50;
      const tnm = c.tnm || String(c.net).replace(/[<>]/g, '_');
      const ts = c.name || `TS_${tnm}`;
      lines.push(`NET ${q(c.net)} TNM_NET = ${q(tnm)} ;`);
      lines.push(`TIMESPEC ${q(ts)} = PERIOD ${q(tnm)} ${fmtNum(ns)} ns HIGH ${duty}% ;`);
    }
  }
  return lines.join('\n') + '\n';
}

/** Sort nets: by base name, then numeric bit index. */
function netCompare(a, b) {
  const ma = /^(.*?)(?:<(\d+)>)?$/.exec(a), mb = /^(.*?)(?:<(\d+)>)?$/.exec(b);
  if (ma[1] !== mb[1]) return ma[1].localeCompare(mb[1]);
  return (+(ma[2] ?? -1)) - (+(mb[2] ?? -1));
}

/** Split UCF text into statements (terminated by ';'), stripping '#' comments. */
function statements(text) {
  const clean = String(text).split(/\r?\n/).map(l => {
    // '#' starts a comment unless inside a quoted string.
    let inStr = false;
    for (let i = 0; i < l.length; i++) {
      if (l[i] === '"') inStr = !inStr;
      else if (l[i] === '#' && !inStr) return l.slice(0, i);
    }
    return l;
  }).join('\n');
  const out = [];
  let cur = '', inStr = false;
  for (const ch of clean) {
    if (ch === '"') inStr = !inStr;
    if (ch === ';' && !inStr) { if (cur.trim()) out.push(cur.trim().replace(/\s+/g, ' ')); cur = ''; }
    else cur += ch;
  }
  if (cur.trim()) out.push(cur.trim().replace(/\s+/g, ' '));
  return out;
}

const unq = s => s.trim().replace(/^"(.*)"$/, '$1');

/** Parse 'PERIOD = 20 ns HIGH 50%' / 'PERIOD "tnm" 20 ns HIGH 50%' spec remainders. */
function parsePeriodSpec(s) {
  const m = /([\d.]+)\s*(ps|ns|us|ms|mhz|khz|ghz|hz)?\s*(?:(HIGH|LOW)\s*([\d.]+)\s*%?)?/i.exec(s);
  if (!m) return null;
  const period = periodNs(`${m[1]} ${m[2] || 'ns'}`);
  let duty = m[4] !== undefined ? parseFloat(m[4]) : 50;
  if (m[3] && m[3].toUpperCase() === 'LOW') duty = 100 - duty;
  return { period: +period.toFixed(6), duty };
}

/**
 * Parse UCF text.
 * @returns {{ assignments: Object<string, object>, clocks: Array, other: string[] }}
 */
export function parseUcf(text) {
  const assignments = {};
  const clocks = [];
  const other = [];
  const tnmToNet = {};
  const pendingTs = [];

  for (const st of statements(text)) {
    const mNet = /^NET\s+("[^"]*"|\S+)\s+(.*)$/i.exec(st);
    if (mNet) {
      const net = unq(mNet[1]);
      const rest = mNet[2];
      // Inline PERIOD on a net: NET "clk" PERIOD = 20 ns HIGH 50%;
      const mPer = /^PERIOD\s*=\s*(.*)$/i.exec(rest);
      if (mPer) {
        const p = parsePeriodSpec(mPer[1]);
        if (p) clocks.push({ net, ...p });
        continue;
      }
      const a = assignments[net] || {};
      let touched = false;
      for (const raw of rest.split('|')) {
        const part = raw.trim();
        if (!part) continue;
        const kv = /^([A-Za-z_]+)\s*(?:=\s*(.*))?$/.exec(part);
        if (!kv) { other.push(st); continue; }
        const key = kv[1].toUpperCase();
        const val = kv[2] !== undefined ? unq(kv[2]) : undefined;
        switch (key) {
          case 'LOC': a.loc = val.toUpperCase(); touched = true; break;
          case 'IOSTANDARD': a.iostandard = val.toUpperCase(); touched = true; break;
          case 'PULLUP': a.pull = 'up'; touched = true; break;
          case 'PULLDOWN': a.pull = 'down'; touched = true; break;
          case 'KEEPER': a.pull = 'keeper'; touched = true; break;
          case 'DRIVE': a.drive = parseInt(val, 10); touched = true; break;
          case 'SLEW': a.slew = val.toLowerCase(); touched = true; break;
          case 'CLOCK_DEDICATED_ROUTE': a.clockDedicatedRoute = !/^false$/i.test(val); touched = true; break;
          case 'TNM_NET': case 'TNM': tnmToNet[val] = net; break;
          default: other.push(`NET "${net}" ${part}`);
        }
      }
      if (touched) assignments[net] = a;
      continue;
    }
    const mTs = /^TIMESPEC\s+("[^"]*"|\S+)\s*=\s*PERIOD\s+("[^"]*"|\S+)\s+(.*)$/i.exec(st);
    if (mTs) { pendingTs.push({ name: unq(mTs[1]), tnm: unq(mTs[2]), spec: mTs[3] }); continue; }
    other.push(st);
  }

  for (const t of pendingTs) {
    const p = parsePeriodSpec(t.spec);
    if (!p) { other.push(`TIMESPEC "${t.name}" = PERIOD "${t.tnm}" ${t.spec}`); continue; }
    clocks.push({ net: tnmToNet[t.tnm] ?? t.tnm, name: t.name, tnm: t.tnm, ...p });
  }
  return { assignments, clocks, other };
}

// ---------------------------------------------------------------------------------------------
// Board-driven assignment: match top-level ports to board resources by name
// (clk/clock -> the board clock, led/leds -> LEDs, sw/switches, btn/buttons, seg, an, ...).
// ports: [{ name, dir, width, msb, lsb }]; board: an entry of BOARDS (server/devices.js).
// Returns { assignments, clocks, matched: [portName], unmatched: [portName] }.
const ALIASES = {
  clock: 'clk', clk_50mhz: 'clk', mclk: 'clk', sysclk: 'clk', clk_in: 'clk',
  leds: 'led', ld: 'led', switches: 'sw', switch: 'sw', sws: 'sw',
  buttons: 'btn', btns: 'btn', button: 'btn', segments: 'seg', sseg: 'seg', anodes: 'an', anode: 'an',
};
export function boardAutoAssign(ports, board) {
  const assignments = {}, clocks = [], matched = [], unmatched = [];
  const res = board?.resources || [];
  const byName = new Map(res.map(r => [r.name.toLowerCase(), r]));
  for (const p of ports) {
    const key = p.name.toLowerCase();
    const alias = ALIASES[key] || key;
    let r = byName.get(key) || byName.get(alias);
    if (!r && alias === 'clk') r = res.find(x => x.group === 'Clock');
    if (!r) { unmatched.push(p.name); continue; }
    const attrs = pin => {
      const a = { loc: pin, iostandard: r.iostandard };
      if (r.pull) a.pull = r.pull;
      if (r.drive) a.drive = r.drive;
      if (r.slew) a.slew = r.slew;
      if (r.clockDedicatedRoute === false) a.clockDedicatedRoute = false;
      return a;
    };
    const width = p.width || 1;
    if (width === 1 && (p.msb === null || p.msb === undefined)) {
      assignments[p.name] = attrs(r.pins[0]);
      if (r.group === 'Clock') clocks.push({ net: p.name, period: periodNs(r.extra?.period || '20 ns'), duty: 50 });
    } else {
      const lo = Math.min(p.msb, p.lsb);
      if (width > r.pins.length) unmatched.push(`${p.name}[${lo + r.pins.length}..]`);
      for (let i = 0; i < Math.min(width, r.pins.length); i++) assignments[bitName(p.name, lo + i)] = attrs(r.pins[i]);
    }
    matched.push(p.name);
  }
  return { assignments, clocks, matched, unmatched };
}

// LOCs of a parsed UCF that are not pins of the given board (or of any of its resources).
export function locsNotOnBoard(assignments, board) {
  const pins = new Set((board?.resources || []).flatMap(r => r.pins.map(p => p.toUpperCase())));
  if (!pins.size) return [];
  return Object.entries(assignments).filter(([, a]) => a.loc && !pins.has(a.loc.toUpperCase())).map(([net, a]) => ({ net, loc: a.loc }));
}
